"""One-shot patch: extend notebook 05 with batch diagnostics and rename."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "notebooks" / "05_cell_composition_analysis.ipynb"
DST = ROOT / "notebooks" / "05_biological_and_batch_effect_analysis.ipynb"

with SRC.open(encoding="utf-8") as f:
    nb = json.load(f)

# Ensure GEOparse is listed for restart-run-all (external cohort SOFT parsing).
for cell in nb["cells"]:
    if cell.get("cell_type") != "code":
        continue
    src = "".join(cell.get("source", []))
    if "%pip install" in src and "GEOparse" not in src:
        cell["source"] = [
            "%pip install -q pandas numpy scipy scikit-learn matplotlib "
            "joblib pyarrow seaborn GEOparse\n"
        ]
        break

# Update title cell (first markdown)
nb["cells"][0]["source"] = [
    "# 05 — Biological validation: cell composition & batch-effect diagnostics\n",
    "\n",
    "This notebook (1) estimates **whole-blood leukocyte proportions** from Illumina 450K betas using a **Houseman-style constrained projection** against the **Reinius** reference (`450K_reinius_12_reference.csv` from Biolearn), and correlates **`age_acceleration`** with inferred fractions.\n",
    "\n",
    "(2) **Batch-effect diagnostics:** combine **GSE40279** (training cohort) and **GSE87571** (external validation cohort) on the **same model CpGs**, run **PCA**, optional **UMAP**, distribution comparisons, and a **cohort classifier** to probe whether methylation space separates studies (technical structure) independently of age.\n",
    "\n",
    "**Prerequisites:** `01_data_loading.ipynb`, `02_model_training.ipynb`. For external methylation, **`04_external_validation.ipynb`** should have been run once so `data/raw/GSE87571/` matrices exist—or this notebook downloads them the same way.\n",
    "\n",
    "**No ComBat or harmonization** is applied here; this layer is **diagnostic only**.\n",
]

NEW_CELLS = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Batch-effect diagnostics (GSE40279 vs GSE87571)\n",
            "\n",
            "External validation compares clocks across **different laboratories, preprocessing choices, and population composition**. DNA methylation is highly sensitive to **batch** and **biological** drivers; strong **cohort separability** in probe space suggests that apparent cross-study agreement could partly reflect **shared technical structure** rather than pure aging biology.\n",
            "\n",
            "This section builds a **combined matrix** restricted to **`selected_cpgs`** that exist in both cohorts, then performs **PCA**, optional **UMAP**, age/cohort distribution checks, and a simple **cohort classifier**. High classifier performance indicates easy **study discrimination**—a flag for batch dominance, not proof that the clock is invalid.\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Why batch effects matter\n",
            "\n",
            "- **Illumina arrays** integrate dye bias, bisulfite conversion, and normalization choices that differ by study.\n",
            "- **Whole blood** mixes cell types; cohorts differ in age range and ancestry, which interact with technical factors.\n",
            "- **Biological signal** (age-related CpG drift) can be **entangled** with **technical cohort structure** when validation uses public supplementary betas processed differently from training.\n",
            "\n",
            "**Difference:** *Biological aging signal* is covariance with chronological age within a harmonized design; *technical cohort structure* is systematic divergence between studies that may align with age covariates by accident.\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Load external cohort (same pattern as `04_external_validation.ipynb`)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "import re\n",
            "import urllib.request\n",
            "\n",
            "import GEOparse\n",
            "import matplotlib.pyplot as plt\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "from sklearn.decomposition import PCA\n",
            "from sklearn.ensemble import RandomForestClassifier\n",
            "from sklearn.linear_model import LogisticRegression\n",
            "from sklearn.metrics import accuracy_score, roc_auc_score\n",
            "from sklearn.model_selection import train_test_split\n",
            "from sklearn.pipeline import Pipeline\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "\n",
            "RAW_DIR = DATA_DIR / \"raw\"\n",
            "EXT_SUBDIR = RAW_DIR / \"GSE87571\"\n",
            "EXT_SUBDIR.mkdir(parents=True, exist_ok=True)\n",
            "EXT_GSE = \"GSE87571\"\n",
            "\n",
            "BASE_SUPPL = \"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE87nnn/GSE87571/suppl/\"\n",
            "downloads = {\n",
            "    \"GSE87571_matrix1of2.txt.gz\": BASE_SUPPL + \"GSE87571_matrix1of2.txt.gz\",\n",
            "    \"GSE87571_matrix2of2.txt.gz\": BASE_SUPPL + \"GSE87571_matrix2of2.txt.gz\",\n",
            "}\n",
            "for fname, url in downloads.items():\n",
            "    dest = EXT_SUBDIR / fname\n",
            "    if not dest.is_file():\n",
            "        print(\"Downloading\", fname, \"…\")\n",
            "        urllib.request.urlretrieve(url, dest)\n",
            "    else:\n",
            "        print(\"Using existing\", fname)\n",
            "\n",
            "\n",
            "def read_probe_by_sample_matrix(path: Path) -> pd.DataFrame:\n",
            "    df = pd.read_csv(path, sep=\"\\t\", compression=\"gzip\", low_memory=False)\n",
            "    probe_col = df.columns[0]\n",
            "    df = df.rename(columns={probe_col: \"probe_id\"}).set_index(\"probe_id\")\n",
            "    df.columns = df.columns.astype(str)\n",
            "    for c in df.columns:\n",
            "        df[c] = pd.to_numeric(df[c], errors=\"coerce\")\n",
            "    return df\n",
            "\n",
            "\n",
            "m1 = read_probe_by_sample_matrix(EXT_SUBDIR / \"GSE87571_matrix1of2.txt.gz\")\n",
            "m2 = read_probe_by_sample_matrix(EXT_SUBDIR / \"GSE87571_matrix2of2.txt.gz\")\n",
            "if not m1.columns.equals(m2.columns):\n",
            "    raise ValueError(\"GSE87571 matrix halves: column mismatch\")\n",
            "beta_ps = pd.concat([m1, m2], axis=0)\n",
            "X_ext_full = beta_ps.T.astype(\"float32\")\n",
            "X_ext_full.index = X_ext_full.index.astype(str)\n",
            "\n",
            "gse_ext = GEOparse.get_GEO(geo=EXT_GSE, destdir=str(EXT_SUBDIR / \"geo_soft\"), how=\"brief\")\n",
            "\n",
            "\n",
            "def age_from_gsm(gsm) -> float:\n",
            "    chars = gsm.metadata.get(\"characteristics_ch1\", [])\n",
            "    blob = \" \".join(str(x) for x in chars)\n",
            "    m = re.search(r\"(?i)age\\s*:\\s*([0-9]+(?:\\.[0-9]+)?)\", blob)\n",
            "    if m:\n",
            "        return float(m.group(1))\n",
            "    compact = re.sub(r\"\\s+\", \"\", blob)\n",
            "    m2 = re.search(r\"(?i)age:([0-9]+(?:\\.[0-9]+)?)\", compact)\n",
            "    if m2:\n",
            "        return float(m2.group(1))\n",
            "    return float(\"nan\")\n",
            "\n",
            "\n",
            "age_ext = pd.Series(\n",
            "    {gid: age_from_gsm(gsm) for gid, gsm in gse_ext.gsms.items()},\n",
            "    dtype=float,\n",
            ").dropna()\n",
            "age_ext.index = age_ext.index.astype(str)\n",
            "\n",
            "gsm_ids = {str(k) for k in gse_ext.gsms.keys()}\n",
            "frac_gsm = float(np.mean([i in gsm_ids for i in X_ext_full.index]))\n",
            "if frac_gsm < 0.5:\n",
            "    title_to_gsm = {}\n",
            "    for gid, gsm in gse_ext.gsms.items():\n",
            "        gid = str(gid)\n",
            "        for t in gsm.metadata.get(\"title\", []) or []:\n",
            "            ts = str(t).strip()\n",
            "            title_to_gsm[ts] = gid\n",
            "            m = re.search(r\"(?i)^X(\\d+)\\b\", ts)\n",
            "            if m:\n",
            "                title_to_gsm[\"X\" + m.group(1)] = gid\n",
            "    X_ext_full.index = [\n",
            "        i if i in gsm_ids else title_to_gsm.get(i, i) for i in X_ext_full.index\n",
            "    ]\n",
            "    if pd.Index(X_ext_full.index).duplicated().any():\n",
            "        X_ext_full = X_ext_full[~pd.Index(X_ext_full.index).duplicated(keep=\"first\")]\n",
            "\n",
            "ext_cols = set(X_ext_full.columns.astype(str))\n",
            "int_cols = set(X.columns.astype(str))\n",
            "overlap_cpgs = [c for c in selected_cpgs if c in ext_cols and c in int_cols]\n",
            "print(\"Model candidate CpGs:\", len(selected_cpgs))\n",
            "print(\"Overlapping CpGs (both cohorts):\", len(overlap_cpgs))\n",
            "missing_probes = [c for c in selected_cpgs if c not in ext_cols]\n",
            "print(\"Training probes missing from external matrix:\", len(missing_probes))\n",
            "\n",
            "X_int = X[overlap_cpgs].copy()\n",
            "common_ext = X_ext_full.index.intersection(age_ext.index)\n",
            "X_ext_sub = X_ext_full.loc[common_ext, overlap_cpgs].dropna(how=\"any\")\n",
            "y_ext_a = age_ext.loc[X_ext_sub.index]\n",
            "\n",
            "# Same leakage-safe Z as `04_external_validation.ipynb`: present probes scaled;\n",
            "# absent probes → z=0.\n",
            "mean_tr = scaler.mean_\n",
            "scale_tr = scaler.scale_\n",
            "scale_safe = np.where(scale_tr == 0, 1.0, scale_tr)\n",
            "sub_z = X_ext_full.reindex(index=X_ext_sub.index)\n",
            "Z_ext = np.zeros((len(X_ext_sub), len(selected_cpgs)), dtype=np.float64)\n",
            "for j, cpg in enumerate(selected_cpgs):\n",
            "    if cpg not in sub_z.columns:\n",
            "        Z_ext[:, j] = 0.0\n",
            "        continue\n",
            "    col = sub_z[cpg].to_numpy(dtype=np.float64)\n",
            "    Z_ext[:, j] = (col - mean_tr[j]) / scale_safe[j]\n",
            "\n",
            "pred_ext = pd.Series(\n",
            "    model.predict(Z_ext), index=X_ext_sub.index, name=\"predicted_age\"\n",
            ")\n",
            "\n",
            "meta_int = pd.DataFrame(\n",
            "    {\n",
            "        \"sample_id\": X_int.index.astype(str),\n",
            "        \"cohort\": \"GSE40279\",\n",
            "        \"chronological_age\": y_age.loc[X_int.index].values,\n",
            "        \"predicted_age\": pred_age.loc[X_int.index].values,\n",
            "        \"age_acceleration\": (\n",
            "            pred_age.loc[X_int.index] - y_age.loc[X_int.index]\n",
            "        ).values,\n",
            "    }\n",
            ").set_index(\"sample_id\")\n",
            "\n",
            "meta_ext = pd.DataFrame(\n",
            "    {\n",
            "        \"sample_id\": X_ext_sub.index.astype(str),\n",
            "        \"cohort\": \"GSE87571\",\n",
            "        \"chronological_age\": y_ext_a.values,\n",
            "        \"predicted_age\": pred_ext.loc[X_ext_sub.index].values,\n",
            "        \"age_acceleration\": (\n",
            "            pred_ext.loc[X_ext_sub.index] - y_ext_a\n",
            "        ).values,\n",
            "    }\n",
            ").set_index(\"sample_id\")\n",
            "\n",
            "batch_meta = pd.concat([meta_int, meta_ext], axis=0)\n",
            "batch_meta_path = RESULTS_DIR / \"cohort_batch_metadata.csv\"\n",
            "batch_meta.to_csv(batch_meta_path, index_label=\"sample_id\")\n",
            "print(\"Combined metadata rows:\", batch_meta.shape[0])\n",
            "display(batch_meta.head())\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### PCA on combined methylation (overlapping model CpGs)\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "X_combined = pd.concat(\n",
            "    [\n",
            "        X_int,\n",
            "        X_ext_full.loc[X_ext_sub.index, overlap_cpgs],\n",
            "    ],\n",
            "    axis=0,\n",
            ").astype(np.float64)\n",
            "\n",
            "meta_aligned = batch_meta.loc[X_combined.index]\n",
            "\n",
            "pca = PCA(n_components=2, random_state=RANDOM_STATE)\n",
            "X_pca = pca.fit_transform(StandardScaler().fit_transform(X_combined))\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(7, 6))\n",
            "for lab, color in zip([\"GSE40279\", \"GSE87571\"], [\"#1f77b4\", \"#ff7f0e\"]):\n",
            "    m = meta_aligned[\"cohort\"] == lab\n",
            "    ax.scatter(\n",
            "        X_pca[m, 0],\n",
            "        X_pca[m, 1],\n",
            "        s=22,\n",
            "        alpha=0.65,\n",
            "        label=lab,\n",
            "        c=color,\n",
            "    )\n",
            "ax.set_xlabel(\"PC1 ({:.1f}% var)\".format(100 * pca.explained_variance_ratio_[0]))\n",
            "ax.set_ylabel(\"PC2 ({:.1f}% var)\".format(100 * pca.explained_variance_ratio_[1]))\n",
            "ax.set_title(\"PCA of combined betas — colored by cohort\")\n",
            "ax.legend()\n",
            "fig.tight_layout()\n",
            "pca_cohort_path = RESULTS_DIR / \"pca_by_cohort.png\"\n",
            "fig.savefig(pca_cohort_path, dpi=150)\n",
            "plt.show()\n",
            "\n",
            "fig2, ax2 = plt.subplots(figsize=(7, 6))\n",
            "sc = ax2.scatter(\n",
            "    X_pca[:, 0],\n",
            "    X_pca[:, 1],\n",
            "    c=meta_aligned[\"chronological_age\"].values,\n",
            "    cmap=\"viridis\",\n",
            "    s=22,\n",
            "    alpha=0.75,\n",
            ")\n",
            "fig2.colorbar(sc, ax=ax2, label=\"Chronological age\")\n",
            "ax2.set_xlabel(\"PC1\")\n",
            "ax2.set_ylabel(\"PC2\")\n",
            "ax2.set_title(\"PCA of combined betas — colored by chronological age\")\n",
            "fig2.tight_layout()\n",
            "pca_age_path = RESULTS_DIR / \"pca_by_age.png\"\n",
            "fig2.savefig(pca_age_path, dpi=150)\n",
            "plt.show()\n",
            "\n",
            "for pth in (pca_cohort_path, pca_age_path):\n",
            "    shutil.copy2(pth, PUBLIC_DIR / pth.name)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Optional UMAP\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "try:\n",
            "    import umap\n",
            "\n",
            "    reducer = umap.UMAP(n_components=2, random_state=RANDOM_STATE)\n",
            "    X_um = reducer.fit_transform(StandardScaler().fit_transform(X_combined))\n",
            "    figu, axu = plt.subplots(figsize=(7, 6))\n",
            "    for lab, color in zip([\"GSE40279\", \"GSE87571\"], [\"#1f77b4\", \"#ff7f0e\"]):\n",
            "        m = meta_aligned[\"cohort\"] == lab\n",
            "        axu.scatter(\n",
            "            X_um[m, 0], X_um[m, 1], s=22, alpha=0.65, label=lab, c=color\n",
            "        )\n",
            "    axu.set_title(\"UMAP — cohort\")\n",
            "    axu.legend()\n",
            "    figu.tight_layout()\n",
            "    upath = RESULTS_DIR / \"umap_by_cohort.png\"\n",
            "    figu.savefig(upath, dpi=150)\n",
            "    plt.show()\n",
            "    shutil.copy2(upath, PUBLIC_DIR / upath.name)\n",
            "    figu2, axu2 = plt.subplots(figsize=(7, 6))\n",
            "    sc_age = axu2.scatter(\n",
            "        X_um[:, 0],\n",
            "        X_um[:, 1],\n",
            "        c=meta_aligned[\"chronological_age\"].values,\n",
            "        cmap=\"viridis\",\n",
            "        s=22,\n",
            "        alpha=0.75,\n",
            "    )\n",
            "    figu2.colorbar(sc_age, ax=axu2, label=\"Age\")\n",
            "    axu2.set_title(\"UMAP — chronological age\")\n",
            "    figu2.tight_layout()\n",
            "    upath2 = RESULTS_DIR / \"umap_by_age.png\"\n",
            "    figu2.savefig(upath2, dpi=150)\n",
            "    plt.show()\n",
            "    shutil.copy2(upath2, PUBLIC_DIR / upath2.name)\n",
            "except ImportError:\n",
            "    print(\n",
            "        \"umap-learn not installed; skip UMAP. Optional: pip install umap-learn\"\n",
            "    )\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Age and predicted-age distributions by cohort\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "figd, (axa, axb) = plt.subplots(1, 2, figsize=(11, 4))\n",
            "for lab, color in zip([\"GSE40279\", \"GSE87571\"], [\"#1f77b4\", \"#ff7f0e\"]):\n",
            "    sub = meta_aligned[meta_aligned[\"cohort\"] == lab][\"chronological_age\"]\n",
            "    axa.hist(sub, bins=25, alpha=0.55, label=lab, color=color, density=True)\n",
            "axa.set_xlabel(\"Chronological age\")\n",
            "axa.set_ylabel(\"Density\")\n",
            "axa.set_title(\"Chronological age by cohort\")\n",
            "axa.legend()\n",
            "for lab, color in zip([\"GSE40279\", \"GSE87571\"], [\"#1f77b4\", \"#ff7f0e\"]):\n",
            "    sub = meta_aligned[meta_aligned[\"cohort\"] == lab][\"predicted_age\"]\n",
            "    axb.hist(sub, bins=25, alpha=0.55, label=lab, color=color, density=True)\n",
            "axb.set_xlabel(\"Predicted age (frozen clock)\")\n",
            "axb.set_ylabel(\"Density\")\n",
            "axb.set_title(\"Predicted age by cohort\")\n",
            "axb.legend()\n",
            "figd.tight_layout()\n",
            "dist_path = RESULTS_DIR / \"cohort_age_prediction_distributions.png\"\n",
            "figd.savefig(dist_path, dpi=150)\n",
            "plt.show()\n",
            "shutil.copy2(dist_path, PUBLIC_DIR / dist_path.name)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Cohort separability classifier\n",
            "\n",
            "Train a simple model to predict **which study** a sample belongs to from **raw overlapping betas**. **ROC-AUC** near 1.0 means methylation features separate cohorts almost perfectly—consistent with strong batch/study-specific structure (not proof that external validation is \"wrong,\" but a warning that signals may be partially study-specific).\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "y_cohort = (meta_aligned[\"cohort\"] == \"GSE87571\").astype(int).values\n",
            "X_mat = X_combined.values\n",
            "X_clf_tr, X_clf_te, y_clf_tr, y_clf_te = train_test_split(\n",
            "    X_mat,\n",
            "    y_cohort,\n",
            "    test_size=0.25,\n",
            "    random_state=RANDOM_STATE,\n",
            "    stratify=y_cohort,\n",
            ")\n",
            "\n",
            "pipe_lr = Pipeline(\n",
            "    [\n",
            "        (\"scale\", StandardScaler()),\n",
            "        (\n",
            "            \"clf\",\n",
            "            LogisticRegression(\n",
            "                max_iter=5000,\n",
            "                random_state=RANDOM_STATE,\n",
            "                solver=\"lbfgs\",\n",
            "            ),\n",
            "        ),\n",
            "    ]\n",
            ")\n",
            "pipe_lr.fit(X_clf_tr, y_clf_tr)\n",
            "proba_te = pipe_lr.predict_proba(X_clf_te)[:, 1]\n",
            "pred_te = pipe_lr.predict(X_clf_te)\n",
            "auc_lr = float(roc_auc_score(y_clf_te, proba_te))\n",
            "acc_lr = float(accuracy_score(y_clf_te, pred_te))\n",
            "\n",
            "rf = RandomForestClassifier(\n",
            "    n_estimators=200,\n",
            "    random_state=RANDOM_STATE,\n",
            "    n_jobs=-1,\n",
            "    max_depth=12,\n",
            ")\n",
            "rf.fit(X_clf_tr, y_clf_tr)\n",
            "proba_rf = rf.predict_proba(X_clf_te)[:, 1]\n",
            "pred_rf = rf.predict(X_clf_te)\n",
            "auc_rf = float(roc_auc_score(y_clf_te, proba_rf))\n",
            "acc_rf = float(accuracy_score(y_clf_te, pred_rf))\n",
            "\n",
            "clf_metrics = pd.DataFrame(\n",
            "    [\n",
            "        {\n",
            "            \"model\": \"logistic_regression_scaled\",\n",
            "            \"roc_auc_holdout\": auc_lr,\n",
            "            \"accuracy_holdout\": acc_lr,\n",
            "            \"n_features\": X_mat.shape[1],\n",
            "            \"n_train\": int(X_clf_tr.shape[0]),\n",
            "            \"n_test\": int(X_clf_te.shape[0]),\n",
            "        },\n",
            "        {\n",
            "            \"model\": \"random_forest\",\n",
            "            \"roc_auc_holdout\": auc_rf,\n",
            "            \"accuracy_holdout\": acc_rf,\n",
            "            \"n_features\": X_mat.shape[1],\n",
            "            \"n_train\": int(X_clf_tr.shape[0]),\n",
            "            \"n_test\": int(X_clf_te.shape[0]),\n",
            "        },\n",
            "    ]\n",
            ")\n",
            "display(clf_metrics)\n",
            "\n",
            "clf_path = RESULTS_DIR / \"cohort_classifier_metrics.csv\"\n",
            "clf_metrics.to_csv(clf_path, index=False)\n",
            "shutil.copy2(clf_path, PUBLIC_DIR / clf_path.name)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Interpretation (batch vs biology)\n",
            "\n",
            "- **Strong PCA/UMAP separation by cohort** together with **high cohort-classifier AUC** suggests that **study-specific methylation structure** is prominent relative to within-study age gradients projected into two dimensions. That does **not** prove the clock tracks only batch—it means naive cross-cohort visualization highlights technical divergence.\n",
            "- **External validation** can still show reasonable age correlation if **age-aligned signal** overlaps technical axes—but disentangling the two requires **harmonization**, **cell adjustment**, or **prospective** study designs beyond this repository.\n",
            "- This notebook **does not** apply **ComBat** or remove batch effects from predictions; it **flags** when cohort classification is trivially easy.\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### External validation vs batch structure — synthesis\n",
            "\n",
            "- **Biologically plausible signal:** If predicted ages track chronological ages **within** each cohort and **correlations** in notebook 04 are strong, part of the signal is consistent with shared aging biology.\n",
            "- **Cohort-structure caveat:** High separability implies **external metrics** should be interpreted as **transport under technical shift**, not as a pure aging biomarker validation.\n",
            "- **Limitations:** Without **full harmonization** (e.g., ComBat on betas, careful normalization parity, cell-type correction), residual batch effects likely remain; this diagnostic layer **does not replace** those pipelines.\n",
        ],
    },
]

# Insert before last cell (Conclusion template)
idx = len(nb["cells"]) - 1
assert "## Conclusion template" in "".join(nb["cells"][idx]["source"])
nb["cells"][idx:idx] = NEW_CELLS

with DST.open("w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Wrote", DST)
if SRC.resolve() != DST.resolve():
    SRC.unlink()
    print("Removed", SRC)
